"""Initial migration

Revision ID: f3727cbe1bac
Revises: b0f4877d21b1
Create Date: 2025-08-06 19:15:06.679576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3727cbe1bac'
down_revision = 'b0f4877d21b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###