# .github/workflows/build-and-deploy.yml
name: Build and Deploy to Home Assistant Green
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio-frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio-backend:latest

      - name: Deploy to Home Assistant Green (password auth)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOME_ASSISTANT_HOST }}
          username: ${{ secrets.HOME_ASSISTANT_USERNAME }}
          password: ${{ secrets.HOME_ASSISTANT_PASSWORD }}
          port: 22
          script: |
            echo "=== Starting Deployment ==="
            
            # Ensure we're in the home directory
            cd /home
            
            # Check if portfolio directory exists and is a git repository
            if [ -d "portfolio/.git" ]; then
              echo "Repository exists, pulling latest changes..."
              cd portfolio
              git pull origin main
            else
              echo "Repository not found, cloning..."
              # Remove directory if it exists but isn't a git repo
              if [ -d "portfolio" ]; then
                echo "Removing existing non-git portfolio directory..."
                rm -rf portfolio
              fi
              # Clone the repository
              git clone https://github.com/${{ github.repository }}.git portfolio
              cd portfolio
            fi
            
            echo ""
            echo "Current directory: $(pwd)"
            echo "Repository contents:"
            ls -la
            
            # Check for docker-compose.yml in the docker directory
            if [ -f "docker/docker-compose.yml" ]; then
              echo ""
              echo "Found docker-compose.yml in docker/ directory"
              cd docker
              
              # Pull the latest images
              echo "Pulling latest Docker images..."
              docker-compose pull
              
              # Start the services
              echo "Starting services..."
              docker-compose up -d --build
              
              echo ""
              echo "Deployment complete!"
              echo "Running containers:"
              docker ps
            else
              echo "ERROR: docker/docker-compose.yml not found!"
              exit 1
            fi
