# .github/workflows/build-and-deploy.yml
name: Build and Deploy to Home Assistant Green
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio-frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio-backend:latest

      - name: Deploy to Home Assistant Green (password auth)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOME_ASSISTANT_HOST }}
          username: ${{ secrets.HOME_ASSISTANT_USERNAME }}
          password: ${{ secrets.HOME_ASSISTANT_PASSWORD }}
          port: 22
          script: |
            cd /opt/portfolio
            git pull
            docker-compose pull
            docker-compose up -d --build
