name: Build and Deploy to Home Assistant

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy to Home Assistant
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOME_ASSISTANT_HOST }}
          username: ${{ secrets.HOME_ASSISTANT_USERNAME }}
          password: ${{ secrets.HOME_ASSISTANT_PASSWORD }}
          script: |
            cd /home/portfolio/portfolio
            sudo git pull
            echo "--- Docker status before docker-compose down ---"
            sudo docker ps -a
            sudo docker network ls
            sudo docker-compose down || true # Stop existing containers, ignore errors if none are running
            echo "--- Docker status after docker-compose down ---"
            sudo docker ps -a
            sudo docker network ls
            sudo docker-compose up -d --build --force-recreate
